module.exports = {
  apps: [
    {
      name: 'comfort-web',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '/opt/comfort-apartments/comfapart',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      env_file: '.env',
      watch: false,
      max_memory_restart: '500M',
      error_file: '/var/log/comfort/web-error.log',
      out_file: '/var/log/comfort/web-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'comfort-bot',
      script: 'node_modules/.bin/tsx',
      args: 'src/bot/telegram-bot.ts',
      cwd: '/opt/comfort-apartments/comfapart',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      env_file: '.env',
      watch: false,
      max_memory_restart: '200M',
      error_file: '/var/log/comfort/bot-error.log',
      out_file: '/var/log/comfort/bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
}
